import { Inter } from 'next/font/google'
import Link from 'next/link'
import { Analytics } from '@vercel/analytics/react';
import './globals.css'
import '@radix-ui/themes/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

import { Theme } from '@radix-ui/themes'

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
            <Analytics />
                <header>
                    <nav className='bg-slate-200 p-4'>
                        <ul>
                            <li>
                                <Link href='/about'>About</Link>
                            </li>
                        </ul>
                    </nav>
                </header>
                <main className='bg-zinc-300'>
                    <Theme>{children}</Theme>
                    
                </main>
                <footer className='bg-sky-100 p-4'>Footer</footer>
            </body>
        </html>
    )
}
