import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react'
import './globals.css'
import '@radix-ui/themes/styles.css'

import Header from '@/comps/layout/header'
import Footer from '@/comps/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

import { Theme } from '@radix-ui/themes'

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <div className='container'>
                    <Analytics />
                    <Header />
                    <main className='bg-zinc-300'>
                        <Theme>{children}</Theme>
                    </main>
                    <Footer />
                </div>
            </body>
        </html>
    )
}
